account/urls.py
from django.urls import path, re_path, reverse_lazy
from account.views import *
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('register/', register, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,33})/$',
            activate, name='activate'),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('account/', account, name='account'),
    path('subscriber/', subscriber, name='subscriber'),
    path('change-password/', change_password, name='change_password'),
    path('reset-password/',
         auth_views.PasswordResetView.as_view(
             template_name="reset/password_reset_form.html",
             email_template_name = 'reset/password_reset_email.html',
             success_url=reverse_lazy('account:password_reset_done')),
         name='reset_password'),
    path('reset-password-done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="reset/password_reset_done.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="reset/password_reset_confirm.html",
             success_url=reverse_lazy('account:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset-password-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="reset/password_reset_complete.html"),
         name='password_reset_complete'),

]

blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [    
    path('blog/', Blog_postListView.as_view(), name="blog"),
    path('single-blog/<slug:slug>/', Blog_postDetailView.as_view(), name='single_page'),
]

checkout/urls.py
from django.urls import path
from checkout.views import *

app_name = 'checkout'

urlpatterns = [    
    path('checkout/', checkout, name='checkout'),
    path('complete/', completed, name='complete'),
    path('wishlist/', wishlist, name='wishlist'),
    path('error/', error, name='error'),
    path('cart/', cart, name='cart'),
]

contact/urls.py
from django.urls import path
from contact.views import *

app_name = 'contact'

urlpatterns = [    
    path('contact/', ContactView.as_view(), name="contact"), 
    path('contact-us/', contact_us, name='contact_us'),
]

shellshop/urls.py
from account.api.views import CustomAuthToken
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from product.views import *
from product.ckeditor_uploader import views
from django.views.decorators.cache import never_cache
from django.contrib.auth import views as auth_views

from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r"^upload/", views.upload, name="ckeditor_upload"),
    re_path(r"^browse/", never_cache(views.browse), name="ckeditor_browse",),
    re_path('^', include('django.contrib.auth.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('i18n/', include('django.conf.urls.i18n')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('api/', include('product.api.urls')),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('product/', include('product.urls', namespace='product')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('api/v1/checkout/', include('checkout.api.urls',)),
    path('api/auth/login/', CustomAuthToken.as_view()),
)

templates/includes/footer.html
{% load static contact_tags account_tags alliance_tags i18n %}
<footer class="footer-two">
	<!-- brand logo area start -->
	<div class="brand-logo">
		<div class="container">
			<div class="row">
				<div class="col-xs-12">
					<div class="barnd-bg">
						{% get_alliance as alliance %}
						{% for item in alliance %}
							<a href="{{item.url}}"><img src="{{ item.image.url }}" alt="Brand Logo" /></a>
						{% endfor %}
						
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- brand logo section end -->
	<!-- social media section start -->
	<div class="social-media section-padding">
		<div class="container">
			<div class="row">
				<div class="col-sm-6">
					<div class="newsletter newsletter2">
						<h3>{% trans 'newsletter' %}</h3>
						<form action="{% url 'account:subscriber' %}" method="post">
							{% csrf_token %}
							{% get_subs as subs %}
							<div class="form-group">
								{{ subs.email }}
								{% for error in field.errors %}
								<li class="alert-danger">{{ error }}</li>
								{% endfor %}
							</div>
							<input type="submit" value="{% trans 'subscribe' %}" />
						</form>
					</div>
					<div class="social-icons">
						<a href="#"><i class="mdi mdi-facebook"></i></a>
						<a href="#"><i class="mdi mdi-twitter"></i></a>
						<a href="#"><i class="mdi mdi-google-plus"></i></a>
						<a href="#"><i class="mdi mdi-dribbble"></i></a>
						<a href="#"><i class="mdi mdi-rss"></i></a>
					</div>
				</div>
				{% get_form as form %}
				<div class="col-sm-6 col-md-offset-1 col-md-5">
					<div class="newsletter get-touch">
						<h3>{% trans 'get in touch' %}</h3>
						<form method="post" action="{% url 'contact:contact' %}">
							{% csrf_token %}
							{% for field in form %}
							<div class="form-group">
								{{ field }}
								
								{% for error in field.errors %}
								<li class="alert-danger">{{ error }}</li>
								{% endfor %}
							</div>
							{% endfor %}
							<input type="submit" value="{% trans 'send your message' %}" />
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- social media section end -->
	<!-- footer-top area start -->
	<div class="footer-top section-padding">
		<div class="footer-dsc">
			<div class="container">
				<div class="row">
					<div class="col-xs-12 col-sm-6 col-md-3">
						<div class="single-text">
							<div class="footer-title">
								<h4>{% trans 'contact us' %}</h4>
							</div>
							<div class="footer-text">
								<ul>
									<li>
										<i class="mdi mdi-map-marker"></i>
										<p>Flat no 01, House no 02, Vincent,</p>
										<p>Dhaka-1207, Bangladesh</p>
									</li>
									<li>
										<i class="mdi mdi-phone"></i>
										<p>(+880) 19453 821758</p>
										<p>(+880) 19453 813758</p>
									</li>
									<li>
										<i class="mdi mdi-email"></i>
										<p>info@mydomain.com</p>
										<p>username@email.com</p>
									</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-sm-3 col-md-2 wide-mobile">
						<div class="single-text">
							<div class="footer-title">
								<h4>{% trans 'My Account' %}</h4>
							</div>
							<div class="footer-menu">
								<ul>
									<li><a href="{% url 'account:account' %}"><i class="mdi mdi-menu-right"></i>{% trans 'My account' %}</a></li>
									<li><a href="{% url 'checkout:wishlist' %}"><i class="mdi mdi-menu-right"></i>{% trans 'My wishlist' %}</a></li>
									<li><a href="{% url 'checkout:cart' %}"><i class="mdi mdi-menu-right"></i>{% trans 'My cart' %}</a></li>
									<li><a href="{% url 'account:login' %}"><i class="mdi mdi-menu-right"></i>{% trans 'Sign in' %}</a></li>
									<li><a href="{% url 'checkout:checkout' %}"><i class="mdi mdi-menu-right"></i>{% trans 'Checkout' %}</a></li>
									<li><a href="#"><i class="mdi mdi-menu-right"></i>{% trans 'Track My Order' %}</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-sm-3 col-md-2 wide-mobile">
						<div class="single-text">
							<div class="footer-title">
								<h4>{% trans 'shipping' %}</h4>
							</div>
							<div class="footer-menu">
								<ul>
									<li><a href="contact.html"><i class="mdi mdi-menu-right"></i>{% trans 'New Products' %}</a></li>
									<li><a href="#"><i class="mdi mdi-menu-right"></i>{% trans 'Top Sellers' %}</a></li>
									<li><a href="#"><i class="mdi mdi-menu-right"></i>{% trans 'Manufactirers' %}</a></li>
									<li><a href="#"><i class="mdi mdi-menu-right"></i>{% trans 'Suppliers' %}</a></li>
									<li><a href="#"><i class="mdi mdi-menu-right"></i>{% trans 'Specials' %}</a></li>
									<li><a href="#"><i class="mdi mdi-menu-right"></i>{% trans 'Availability' %}</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-sm-6 col-md-2 r-margin-top wide-mobile">
						<div class="single-text">
							<div class="footer-title">
								<h4>{% trans 'Information' %}</h4>
							</div>
							<div class="footer-menu">
								<ul>
									<li><a href="contact.html"><i class="mdi mdi-menu-right"></i>{% trans 'Return Exchange' %}</a>
									</li>
									<li><a href="#"><i class="mdi mdi-menu-right"></i>{% trans 'Fast Delivery' %}</a></li>
									<li><a href="#"><i class="mdi mdi-menu-right"></i>{% trans 'Online Shopping' %}</a></li>
									<li><a href="#"><i class="mdi mdi-menu-right"></i>{% trans 'Shipping Guide' %}</a></li>
									<li><a href="#"><i class="mdi mdi-menu-right"></i>{% trans 'Turn Of Use' %}</a></li>
									<li><a href="#"><i class="mdi mdi-menu-right"></i>{% trans 'Home Delivery' %}</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-sm-6 col-md-3 r-margin-top wide-mobile">
						<div class="single-text">
							<div class="footer-title">
								<h4>instagram</h4>
							</div>
							<div class="clearfix instagram">
								<ul>
									<li><a href="#"><img src="{% static 'assets/img/footer/in1.png'%}"
												alt="Instagram" /></a></li>
									<li><a href="#"><img src="{% static 'assets/img/footer/in2.png'%}"
												alt="Instagram" /></a></li>
									<li><a href="#"><img src="{% static 'assets/img/footer/in3.png'%}"
												alt="Instagram" /></a></li>
									<li><a href="#"><img src="{% static 'assets/img/footer/in4.png'%}"
												alt="Instagram" /></a></li>
									<li><a href="#"><img src="{% static 'assets/img/footer/in5.png'%}"
												alt="Instagram" /></a></li>
									<li><a href="#"><img src="{% static 'assets/img/footer/in6.png'%}"
												alt="Instagram" /></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- footer-top area end -->
	<!-- footer-bottom area start -->
	<div class="footer-bottom">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-6">
					<p>&copy; Sellshop 2021. All Rights Reserved.</p>
				</div>
				<div class="col-xs-12 col-sm-6 text-right">
					<a href="#"><img src="{% static 'assets/img/footer/payment.png'%}" alt="" /></a>
				</div>
			</div>
		</div>
	</div>
	<!-- footer-bottom area end -->
</footer>
<!-- footer section end -->